/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudiesRouteImport } from './routes/_authenticated/studies'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDirectRouteImport } from './routes/_authenticated/direct'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDirectConversationIdRouteImport } from './routes/_authenticated/direct.$conversationId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudiesRoute = AuthenticatedStudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDirectRoute = AuthenticatedDirectRouteImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDirectConversationIdRoute =
  AuthenticatedDirectConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedDirectRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/direct': typeof AuthenticatedDirectRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/studies': typeof AuthenticatedStudiesRoute
  '/direct/$conversationId': typeof AuthenticatedDirectConversationIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/direct': typeof AuthenticatedDirectRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/studies': typeof AuthenticatedStudiesRoute
  '/direct/$conversationId': typeof AuthenticatedDirectConversationIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/direct': typeof AuthenticatedDirectRouteWithChildren
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/studies': typeof AuthenticatedStudiesRoute
  '/_authenticated/direct/$conversationId': typeof AuthenticatedDirectConversationIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/direct'
    | '/help'
    | '/meetings'
    | '/moderation'
    | '/profile'
    | '/reminders'
    | '/studies'
    | '/direct/$conversationId'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/direct'
    | '/help'
    | '/meetings'
    | '/moderation'
    | '/profile'
    | '/reminders'
    | '/studies'
    | '/direct/$conversationId'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/direct'
    | '/_authenticated/help'
    | '/_authenticated/meetings'
    | '/_authenticated/moderation'
    | '/_authenticated/profile'
    | '/_authenticated/reminders'
    | '/_authenticated/studies'
    | '/_authenticated/direct/$conversationId'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studies': {
      id: '/_authenticated/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof AuthenticatedStudiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/direct': {
      id: '/_authenticated/direct'
      path: '/direct'
      fullPath: '/direct'
      preLoaderRoute: typeof AuthenticatedDirectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/direct/$conversationId': {
      id: '/_authenticated/direct/$conversationId'
      path: '/$conversationId'
      fullPath: '/direct/$conversationId'
      preLoaderRoute: typeof AuthenticatedDirectConversationIdRouteImport
      parentRoute: typeof AuthenticatedDirectRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDirectRouteChildren {
  AuthenticatedDirectConversationIdRoute: typeof AuthenticatedDirectConversationIdRoute
}

const AuthenticatedDirectRouteChildren: AuthenticatedDirectRouteChildren = {
  AuthenticatedDirectConversationIdRoute:
    AuthenticatedDirectConversationIdRoute,
}

const AuthenticatedDirectRouteWithChildren =
  AuthenticatedDirectRoute._addFileChildren(AuthenticatedDirectRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDirectRoute: typeof AuthenticatedDirectRouteWithChildren
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedStudiesRoute: typeof AuthenticatedStudiesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDirectRoute: AuthenticatedDirectRouteWithChildren,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedStudiesRoute: AuthenticatedStudiesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
